HERBAL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from shop.views import paymenthandler

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('account.urls', namespace='account')),
                  path('vendor/', include('vendor.urls', namespace='vendor')),
                  path('', include('shop.urls', namespace='shop')),
                  path('razorpay/callback/',paymenthandler,name='paymenthandler'),
                  path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='commons/password-reset/password_reset.html',
             subject_template_name='commons/password-reset/password_reset_subject.txt',
             email_template_name='commons/password-reset/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='commons/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='commons/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='commons/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop import views
from django.contrib.auth import views as auth_views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.home, name='category_filter'),
    path('product-category/<slug:slug>/', views.products, name='products'),
  
    path('add_to_cart/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:id>', views.update_cart, name='update_cart'),
    path('del_cart/<int:id>', views.remove_from_cart, name='del_cart'),
    path('cart-list', views.cart_list, name='cart-list'),
    path('buy_now', views.buy_now, name='buy_now'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('view_order/<int:id>', views.view_order, name='view_order'),
    path('invoice/<int:id>', views.invoice, name='invoice'),
    path('my_profile', views.my_profile, name='my_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('details/<int:id>/',views.detail,name="detail"),
    path('addreview/<int:id>/',views.add_review,name="add_review"),
    path('editreview/<int:product_id>/<int:review_id>',views.edit_review,name="edit_review"),
    path('deletereview/<int:product_id>/<int:review_id>',views.delete_review,name="delete_review"),
]

templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="container-fluid">
            <div style="
    color: white;
    padding: 20px;
    text-align: center;
    font-size: xx-large;
    font-family: emoji;
    text-shadow: 2px 2px 5px lightcoral;
">Home Appliances Sales &amp; Service</div>
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'shop:home' %}">Home</a>
                {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>