HERBAL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from shop.views import paymenthandler

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('account.urls', namespace='account')),
                  path('vendor/', include('vendor.urls', namespace='vendor')),
                  path('', include('shop.urls', namespace='shop')),
                  path('razorpay/callback/',paymenthandler,name='paymenthandler'),
                  path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='commons/password-reset/password_reset.html',
             subject_template_name='commons/password-reset/password_reset_subject.txt',
             email_template_name='commons/password-reset/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='commons/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='commons/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='commons/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop import views
from django.contrib.auth import views as auth_views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.home, name='category_filter'),
    path('product-category/<slug:slug>/', views.products, name='products'),
  
    path('add_to_cart/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:id>', views.update_cart, name='update_cart'),
    path('del_cart/<int:id>', views.remove_from_cart, name='del_cart'),
    path('cart-list', views.cart_list, name='cart-list'),
    path('buy_now', views.buy_now, name='buy_now'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('view_order/<int:id>', views.view_order, name='view_order'),
    path('invoice/<int:id>', views.invoice, name='invoice'),
    path('my_profile', views.my_profile, name='my_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('details/<int:id>/',views.detail,name="detail"),
    path('addreview/<int:id>/',views.add_review,name="add_review"),
    path('editreview/<int:product_id>/<int:review_id>',views.edit_review,name="edit_review"),
    path('deletereview/<int:product_id>/<int:review_id>',views.delete_review,name="delete_review"),
]

shop/models.py
from django.db import models

# Create your models here.

shop/views.py
import json
import re
from unicodedata import category
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from account.models import CartItem, OrderDetails, Product,User, Category, ProductOrder, Review
from django.db.models import Sum
from django.db.models import Avg
import razorpay
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest
from account.constants import PaymentStatus
from account.forms import EditUserForm, ReviewForm
 
# authorize razorpay client with API Keys.
razorpay_client = razorpay.Client(
    auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))


def home(request, slug=None):
    products = Product.objects.filter(status=True)
    categories = Category.objects.all()
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = products.filter(category=category)
    return render(request, 'shop/home.html', {'products': products, 'categories': categories})

def detail(request,id):
    product=Product.objects.get(id=id)
    reviews = Review.objects.filter(product=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average=0
    else:
        average = round(average,2)
    context={
        "product":product,
        "reviews":reviews,
        "average":average,
    }
    return render(request,'shop/details.html',context)

def products(request, slug=None):
    products = Product.objects.filter(status=True)
    categories = Category.objects.all()
    category = None
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = products.filter(category=category)
    return render(request, 'shop/products.html', {'products': products,"cat":category, 'categories': categories})


def product_detail(request, slug):
    categories = Category.objects.all()
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'shop/product_detail.html', {'product': product, 'categories': categories})

def remove_from_cart(request,id):
    cart_item = CartItem.objects.get(id=id)
    cart_item.delete()
    messages.info(request,'Cart Item removed Successfully')
    return redirect('shop:cart-list')

def buy_now(request):
    cart_items = CartItem.objects.filter(user=request.user)
    tot_amount = 0
    asum = CartItem.objects.filter(user=request.user).aggregate(Sum('amount'))
    if asum is None:
        tot_amount = 0
    else:
        tot_amount = asum['amount__sum']
    razorpay_order = razorpay_client.order.create(
        {"amount": int(tot_amount) * 100, "currency": "INR", "payment_capture": "1"}
    )
    product_order = ProductOrder()
    product_order.user = request.user
    product_order.provider_order_id=razorpay_order["id"]
    product_order.shipping_address = request.POST['shipping_address']
    product_order.total_order_amount = tot_amount
    product_order.save()

    for cart_item in cart_items:
        order_detail = OrderDetails()
        order_detail.product_order = product_order
        order_detail.amount = cart_item.amount
        order_detail.quantity = cart_item.quantity
        order_detail.product = cart_item.product
        order_detail.save()
        cart_item.delete()
    return render(
        request,
        "shop/payment.html",
        {
            "callback_url": "http://" + "127.0.0.1:8000" + "/razorpay/callback/",
            "razorpay_key": settings.RAZOR_KEY_ID,
            "order": product_order,
        },
    )


# we need to csrf_exempt this url as
# POST request will be made by Razorpay
# and it won't have the csrf token.
@csrf_exempt
def paymenthandler(request):
 
    def verify_signature(response_data):
        return razorpay_client.utility.verify_payment_signature(response_data)

    if "razorpay_signature" in request.POST:
        payment_id = request.POST.get("razorpay_payment_id", "")
        provider_order_id = request.POST.get("razorpay_order_id", "")
        signature_id = request.POST.get("razorpay_signature", "")
        order = ProductOrder.objects.get(provider_order_id=provider_order_id)
        order.payment_id = payment_id
        order.signature_id = signature_id
        order.save()
        if verify_signature(request.POST):
            order.status = PaymentStatus.SUCCESS
            order.save()
            order_items = OrderDetails.objects.filter(product_order=order)
            for order_item in order_items:
                product = order_item.product
                qty = order_item.quantity
                product.current_stock = product.current_stock - qty
                product.save()
            messages.info(request,'Your Payment for the order is successfull')
            return redirect('shop:my_orders')
        else:
            order.status = PaymentStatus.FAILURE
            order.save()
            messages.info(request,'Your Payment for the order is not successfull')
            return redirect('shop:my_orders')
    else:
        payment_id = json.loads(request.POST.get("error[metadata]")).get("payment_id")
        provider_order_id = json.loads(request.POST.get("error[metadata]")).get(
            "order_id"
        )
        order = ProductOrder.objects.get(provider_order_id=provider_order_id)
        order.payment_id = payment_id
        order.status = PaymentStatus.FAILURE
        order.save()
        messages.info(request,'Your Payment for the order is not successfull')
        return redirect('shop:my_orders')


def update_cart(request,id):
    cart_item = CartItem.objects.get(id=id)
    cart_item.quantity = request.POST['quantity']
    cart_item.amount = cart_item.product.price * int(request.POST['quantity'])
    cart_item.save()
    messages.info(request,'Cart Updated Successfully')
    return redirect('shop:cart-list')

def cart_list(request):
    categories = Category.objects.all()
    cart_items = CartItem.objects.filter(user=request.user)
    tot_amount = 0
    asum = CartItem.objects.filter(user=request.user).aggregate(Sum('amount'))
    if asum is None:
        tot_amount = 0
    else:
        tot_amount = asum['amount__sum']
    return render(request, 'shop/cart-list.html', {'cart_items': cart_items, 'categories': categories,'tot_amount':tot_amount})


def add_to_cart(request,id):
    product = Product.objects.get(id=id)
    try:
        cart_item = CartItem.objects.get(product=product,user=request.user)
        cart_item.quantity = cart_item.quantity + 1
        cart_item.amount = cart_item.amount + product.price
    except CartItem.DoesNotExist:
        cart_item = CartItem()
        cart_item.product = product
        cart_item.user = request.user
        cart_item.quantity = 1
        cart_item.amount = product.price
    cart_item.save()
    messages.info(request,'Product Added to Cart Successfully')
    return redirect('shop:cart-list')



def my_orders(request):
    categories = Category.objects.all()
    product_orders = ProductOrder.objects.filter(user=request.user)
    return render(request,'shop/my_orders.html',{'product_orders':product_orders, 'categories': categories})

def view_order(request,id):
    categories = Category.objects.all()
    product_order = ProductOrder.objects.get(id=id)
    order_items = OrderDetails.objects.filter(product_order=product_order)
    return render(request,'shop/view_order.html',{'product_order':product_order,'order_items':order_items,'categories': categories})

def invoice(request,id):
    categories = Category.objects.all()
    product_order = ProductOrder.objects.get(id=id)
    order_items = OrderDetails.objects.filter(product_order=product_order)
    return render(request,'shop/invoice.html',{'product_order':product_order,'order_items':order_items,'categories': categories})


def my_profile(request):
    return render(request,'shop/my_profile.html')

def edit_profile(request):
    user_form = EditUserForm(data={'full_name':request.user.full_name,'email':request.user.email,'phone_number':request.user.phone_number})
    if request.method == 'POST':
        user_form = EditUserForm(request.POST)
        if user_form.is_valid():
           data = user_form.cleaned_data
           user = User.objects.get(id=request.user.id)
           user.full_name = data['full_name']
           user.phone_number = data['phone_number']
           user.email = data['email']
           user.save()
           messages.info(request,'Profile Updated Successfully')
           return redirect('shop:my_profile')
        else:
            return render(request,'shop/edit_profile.html',{'user_form':user_form})
    else:
        return render(request,'shop/edit_profile.html',{'user_form':user_form})


def add_review(request,id):
    if request.user.is_authenticated:
        product = Product.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.product = product
                data.save()
                return redirect("shop:detail",id)
        else:
            form = ReviewForm()
        return render(request,'shop/details.html',{'form':form})
    else:
        return redirect("accounts:login")

def edit_review(request,product_id,review_id):
    if request.user.is_authenticated:
        product = Product.objects.get(id=product_id)
        review = Review.objects.get(product=product, id=review_id)
        if request.user == review.user:
            if request.method == "POST":
                form = ReviewForm(request.POST,instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating>10) or (data.rating<0):

shop/templates/shop/about.html
{% extends 'base.html' %} {% block content %}
<!-- banner-2 -->
<div class="page-head_agile_info_w3l">

  </div>
  <!-- //banner-2 -->
  <!-- page -->
  <div class="services-breadcrumb">
    <div class="agile_inner_breadcrumb">
      <div class="container">
        <ul class="w3_short">
          <li>
            <a href="administrator/index.html">Home</a>
            <i>|</i>
          </li>
          <li>About Us</li>
        </ul>
      </div>
    </div>
  </div>
  <!-- //page -->

  <!-- about -->
  <div class="welcome py-sm-5 py-4">
    <div class="container py-xl-4 py-lg-2">
      <!-- tittle heading -->
      <h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
        <span>A</span>bout
        <span>U</span>s</h3>
      <!-- //tittle heading -->
      <div class="row">
        <div class="col-lg-6 welcome-left">
          <h3>Welcome</h3>
          <h4 class="my-sm-3 my-2">HealthCare and medicine are major are major sectors in the world. The healthcare aims in providing best medicinal infrastructure to the human beings. Thus the need for medicine research also has increased. Natural medicine or natural cause have become more popular now a days. It has a deep history and traditions. The health is major part of our life, we cannot make negligency in any of the situation, whether it is minor or major disease. In current era the food we intake is not well nutritioned as compared to the days of 90s. Based on the food culture in nowadays the people are suffering from some diseases. Medical Science has given its contribution in almost all the fields it exists.</h4>
          <p>The people are going to the herbal treatment. Today the people are living in tight schedules. They wont spend their time for their health issues, rather they focus on earnings. In the busy schedule people started using capsules,tablets and some other treatments to cure their diseases. That may effect their health with side effects,allergies. </p>
        </div>
        <div class="col-lg-6 welcome-right-top mt-lg-0 mt-sm-5 mt-4">
          <img src="/static/images/photo2.jpg" class="img-fluid" alt=" ">
        </div>
      </div>
    </div>
  </div>

{% endblock %}

shop/templates/shop/cart-list.html
{% extends 'base.html' %} {% block content %}


<!-- page -->
<div class="services-breadcrumb">
  <div class="agile_inner_breadcrumb">
    <div class="container">
      <ul class="w3_short">
        <li>
          <a href="/">Home</a>
          <i>|</i>
        </li>
        <li>Cart List</li>
      </ul>
    </div>
  </div>
</div>
<!-- //page -->

<!-- top Products -->
<div class="ads-grid py-sm-5 py-4">
  <div class="container py-xl-4 py-lg-2">
    <!-- tittle heading -->
    <h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
     Cart List
    </h3>
    <!-- //tittle heading -->
    <div class="row">
      <!-- product left -->
      <div class="agileinfo-ads-display col-lg-12">
        <div class="wrapper">
          <!-- first section -->
          <div class="product-sec1 px-sm-4 px-3 py-sm-5 py-3 mb-4">
            <div class="row">
              {% if cart_items %}
                <table class="table table-stripped table-bordered">
                    <tr>
                        <th>#</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Amount</th>
                        <th>Action</th>
                    </tr>

              {% for cart_item in cart_items %}
              <tr>
                  <td>{{ forloop.counter}}</td>
                  <td>{{ cart_item.product.name}}
                      <br><img src="{{ cart_item.product.image.url}}" width="100"/>
                  </td>
                  <td> <form action="{% url 'shop:update_cart' cart_item.id %}" method="POST">
                    {% csrf_token %}
                    <input type="number" name="quantity" min="1" value="{{ cart_item.quantity}}" style="width:40px;" max="{{ cart_item.product.current_stock }}" />
                    <button type="submit" class="btn btn-primary">Update</button>
                  </form></td>
                  <td>₹{{ cart_item.product.price}}/-</td>
                  <td>₹{{ cart_item.amount}}/-</td>
                  <td>
                      <a class="btn btn-danger" href="{% url 'shop:del_cart' cart_item.id %}" onclick="return confirm('Are you sure you want to delete this?')"><i class="fa fa-trash"></i>Delete</a>
                  </td>
              </tr>
              <tr>
                <td colspan="4" style="text-align:right;">Total Amount</td>
                <td>₹{{tot_amount}}/-</td>
                <td></td>
              </tr>
              {% endfor %}
            </table>
            {% if tot_amount > 0 %}
                <div class="col-md-12">
                    
                    <form action="{% url 'shop:buy_now' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                          <label>Shipping Address:</label>
                          <input type="text" name="shipping_address" required class="form-control" />
                      </div>
                       
                    <button class="btn btn-success" type="submit">Buy Now</button>

                    </form>
                </div>
                
                    {% endif %}
            {% else %}
            <p> No Items in Cart </p>
            {% endif %}
            </div>
            <!-- //first section -->
          </div>
        </div>
        <!-- //product left -->
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

shop/templates/shop/details.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
	<br>
	<div class="card">
		<div class="row">
			<div class="col-md-4">
				<img src= "/media/{{ product.image }}" width="100" alt="image" class="img-fluid">
				
				<h3>{{ product.name }}</h3>
			</div>
			<div class="col-md-8">
				<p>Product category: {{ product.category.name }}</p>
				<p>Product supplier: {{ product.vendor.full_name }}</p>
				<p>Product Price: {{ product.price }}</p>
				<p>Product rating:{{ average }}/10</p>
				<p>Product description: {{ product.description }}</p>
				
			</div>
		</div>
	</div>

<br>
<div class="card">
	<div class="card=-body">
		<h3 class="text-center">Reviews</h3>
		{% if user.is_authenticated %}
		<form action="{% url 'shop:add_review' product.id %}" method="POST">
			{% csrf_token %}
			<label for="comment">Review</label>
			<textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>
			<label for="rating">Rating</label>
			<input type="range" id="rangeInput" name="rating" min="0" max="10" value="0" step="0.5" oninput="amount.value=rangeInput.value">
			<output name="amount" id="amount" for="rangeInput">0</output>
			<br>
			<input type="submit" class="btn btn-danger" value="Add Review">
		</form>
		{% endif %}
	</div></div>
	<br>
	<div class="card" style="background-color: black;">
		<div class="card-body" style="background:white;">
			<h3 class="text-center">Reviews</h3>
			{% for review in reviews %}
			<div class="row">
				<div class="col-md-3">
					<h5 class="test-left">{{ review.user.username }}</h5>
					<h5>{{ review.rating }}</h5>
					{% if request.user == review.user %}
					<a href="{% url 'shop:edit_review' product.id review.id %}">Edit</a>
					<a href="{% url 'shop:delete_review' product.id review.id %}" onclick="return confirm('Are you sure want to delete this?');">Delete</a>
					{% endif %}
				</div>
				<div class="col-md-9">
					<p>{{ review.comment }}</p>
				</div>
			</div>
	<br>
	{% endfor %}</div></div>
</div>
</div>
{% endblock %}

shop/templates/shop/edit_profile.html
{% extends 'base.html' %} {% block content %}


<!-- page -->
<div class="services-breadcrumb">
  <div class="agile_inner_breadcrumb">
    <div class="container">
      <ul class="w3_short">
        <li>
          <a href="/">Home</a>
          <i>|</i>
        </li>
        <li>My Orders</li>
      </ul>
    </div>
  </div>
</div>
<!-- //page -->

<!-- top Products -->
<div class="ads-grid py-sm-5 py-4">
  <div class="container py-xl-4 py-lg-2">
    <!-- tittle heading -->
    <h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
     Edit Profile
    </h3>
    <!-- //tittle heading -->
    <div class="row">
      <!-- product left -->
      <div class="agileinfo-ads-display col-lg-12">
        <div class="wrapper">
          <!-- first section -->
          <div class="product-sec1 px-sm-4 px-3 py-sm-5 py-3 mb-4">
            <div class="row">
                <form action="#" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ user_form }}
                <button type="submit" class="btn btn-primary">Update Profile</button>

                </form>
            </div>
            <!-- //first section -->
          </div>
        </div>
        <!-- //product left -->
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

shop/templates/shop/editreview.html
{% extends 'base.html' %}



{% block content %}

<div class="container">
	<div class="card">
		<div class="card-body">
			<h3 class="text-center">Edit Review</h3>
			<form action="" method="POST">
				{% csrf_token %}
				{{ form  }}
				{% if error %}
					<strong style="color:red;">{{ error }}</strong>
				{% endif %}
				<input type="submit" value="Save Changes" class="btn btn-danger">
			</form>
		</div>
	</div>
</div>
{% endblock %}

shop/templates/shop/my_orders.html
{% extends 'base.html' %} {% block content %}


<!-- page -->
<div class="services-breadcrumb">
  <div class="agile_inner_breadcrumb">
    <div class="container">
      <ul class="w3_short">
        <li>
          <a href="/">Home</a>
          <i>|</i>
        </li>
        <li>My Orders</li>
      </ul>
    </div>
  </div>
</div>
<!-- //page -->

<!-- top Products -->
<div class="ads-grid py-sm-5 py-4">
  <div class="container py-xl-4 py-lg-2">
    <!-- tittle heading -->
    <h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
     My Orders
    </h3>
    <!-- //tittle heading -->
    <div class="row">
      <!-- product left -->
      <div class="agileinfo-ads-display col-lg-12">
        <div class="wrapper">
          <!-- first section -->
          <div class="product-sec1 px-sm-4 px-3 py-sm-5 py-3 mb-4">
            <div class="row">
              {% if product_orders %}
                <table class="table table-stripped table-bordered">
                    <tr>
                        <th>#</th>
                        <th>Order Date</th>
                        <th>Order Status</th>
                        <th>Payment Status</th>
                        <th>Total Order Amount</th>
                        <th>Action</th>
                    </tr>

              {% for product_order in product_orders %}
              <tr>
                  <td>{{ forloop.counter}}</td>
                  <td>{{ product_order.order_date}}</td>
                  <td>{{ product_order.order_status}}</td>
                  <td>{{ product_order.status}}</td>
                  <td>₹{{ product_order.total_order_amount}}/-</td>
                  <td><a class="btn btn-primary" href="{% url 'shop:view_order' product_order.id %}">View Order</a>{% if product_order.status == 'Success' %} <a class="btn btn-primary" href="{% url 'shop:invoice' product_order.id %}">Invoice</a>{% endif %}</td>

              </tr>
              {% endfor %}
            </table>
            {% else %}
            <p> No Items in My Orders </p>
            {% endif %}
            </div>
            <!-- //first section -->
          </div>
        </div>
        <!-- //product left -->
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

shop/templates/shop/my_profile.html
{% extends 'base.html' %} {% block content %}


<!-- page -->
<div class="services-breadcrumb">
  <div class="agile_inner_breadcrumb">
    <div class="container">
      <ul class="w3_short">
        <li>
          <a href="/">Home</a>
          <i>|</i>
        </li>
        <li>My Orders</li>
      </ul>
    </div>
  </div>
</div>
<!-- //page -->

<!-- top Products -->
<div class="ads-grid py-sm-5 py-4">
  <div class="container py-xl-4 py-lg-2">
    <!-- tittle heading -->
    <h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
     My Profile
    </h3>
    <!-- //tittle heading -->
    <div class="row">
      <!-- product left -->
      <div class="agileinfo-ads-display col-lg-12">
        <div class="wrapper">
          <!-- first section -->
          <div class="product-sec1 px-sm-4 px-3 py-sm-5 py-3 mb-4">
            <div class="row">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                            <tr>
                            
                                <th>Name</th>
                                
                                <th>Mobile</th>
                                <th>Email</th>
                                <th>Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            
                            <tr>
                                
                                <td>{{user.full_name}}</td>
                                
                                <td>{{user.phone_number}}</td>
                                <td>{{user.email}}</td>
                                <td><a class="btn btn-primary" href="{% url 'shop:edit_profile' %}">Edit</a></td>
                                
                            </tr>
                            
                        </tbody>
                    </table>
            </div>
            <!-- //first section -->
          </div>
        </div>
        <!-- //product left -->
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

shop/templates/shop/product_detail.html
{% extends 'base.html' %}



{% block content %}
    <h3>{{ product.name }}</h3>
    <h3>vendor:{{ product.vendor.full_name }}</h3>
    <small>{{ product.created }}</small>
    <p>{{ product.price }} /-</p>
    <img src="{{ product.image.url }}" width="400px" height="400px" alt="{{ product.name }}">
    <hr/>
    <p>{{ product.description }}</p>
    
{% endblock %}

shop/templates/shop/products.html
{% extends 'base.html' %} {% block content %}
<!-- banner-2 -->
<div class="page-head_agile_info_w3l">

</div>
<!-- //banner-2 -->

<!-- page -->
<div class="services-breadcrumb">
  <div class="agile_inner_breadcrumb">
    <div class="container">
      <ul class="w3_short">
        <li>
          <a href="index.html">Home</a>
          <i>|</i>
        </li>
        <li>Herbal Products</li>
      </ul>
    </div>
  </div>
</div>
<!-- //page -->

<!-- top Products -->
<div class="ads-grid py-sm-5 py-4">
  <div class="container py-xl-4 py-lg-2">
    <!-- tittle heading -->
    <h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
      {{ category.name }}
    </h3>
    <!-- //tittle heading -->
    <div class="row">
      <!-- product left -->
      <div class="agileinfo-ads-display col-lg-9">
        <div class="wrapper">
          <!-- first section -->
          <div class="product-sec1 px-sm-4 px-3 py-sm-5 py-3 mb-4">
            <div class="row">
              {% for product in products %}
              <div class="col-md-4 product-men">
                <div class="men-pro-item simpleCart_shelfItem">
                  <div class="men-thumb-item text-center">
                    <img src="/media/{{ product.image }}" alt="" width="200" />
                    <div class="men-cart-pro">
                      <div class="inner-men-cart-pro">
                        <a href="{% url 'shop:detail' product.id %}" class="link-product-add-cart"
                          >Quick View</a
                        >
                      </div>
                    </div>
                  </div>
                  <div class="item-info-product text-center border-top mt-4">
                    <h4 class="pt-1">
                      <a href="#">{{ product.name }}</a>
                      <p><b>Supplier: {{ product.vendor.full_name }}</b></p>
                      <p><b>Description:{{product.description}}</b></p>
                    </h4>
                    <div class="info-product-price my-2">
                      <span class="item_price">₹{{ product.price }}/-</span>
                    </div>
                    <div
                      class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out"
                    >
                    {% if user.is_authenticated %}
                      {% if product.current_stock > 0 %}
                      <form action="{% url 'shop:add_to_cart' product.id %}" method="post">
                        {% csrf_token %}
                        <fieldset>
                          <input
                            type="submit"
                            name="submit"
                            value="Add to cart"
                            class="button btn"
                          />
                        </fieldset>
                      </form>
                      {% else %}
                      <a data-toggle="modal" data-target="#exampleModal" class="btn btn-danger">Out Of Stock</a>
                      {% endif %}
                      {% else %}
                        <a data-toggle="modal" data-target="#exampleModal" class="btn btn-primary">Add to Cart</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- //first section -->
          </div>
        </div>
        <!-- //product left -->
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>