HERBAL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from shop.views import paymenthandler

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('account.urls', namespace='account')),
                  path('vendor/', include('vendor.urls', namespace='vendor')),
                  path('', include('shop.urls', namespace='shop')),
                  path('razorpay/callback/',paymenthandler,name='paymenthandler'),
                  path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='commons/password-reset/password_reset.html',
             subject_template_name='commons/password-reset/password_reset_subject.txt',
             email_template_name='commons/password-reset/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='commons/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='commons/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='commons/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from account import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('vendor_dashboard/', views.vendor_dashboard, name='vendor_dashboard'),
    path('products-list/', views.products_list, name='products-list'),
    path('product-create/', views.add_product, name='product-create'),
    path('product-edit/<int:id>', views.edit_product, name='product_edit'),
    path('product-delete/<int:id>', views.delete_product, name='product_delete'),
    path('categories-list/', views.categories_list, name='categories-list'),
    path('category-create/', views.add_category, name='category-create'),
    path('category-edit/<int:id>', views.edit_category, name='category_edit'),
    path('category-delete/<int:id>', views.delete_category, name='category_delete'),
    path('vendor-list/', views.vendor_list, name='vendor-list'),
    path('vendor-edit/<int:id>', views.edit_vendor, name='vendor_edit'),
    path('vendor-delete/<int:id>', views.delete_vendor, name='vendor_delete'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('vendor_register/', views.vendor_register, name='vendor_register'),
    path('update_order/<int:id>/<str:status>', views.update_order, name='update_order'),
    path('view_order/<int:id>', views.view_order, name='view_order'),
    path('pending_orders/', views.pending_orders, name='pending_orders'),
    path('canceled_orders/', views.canceled_orders, name='canceled_orders'),
    path('delivered_orders/', views.delivered_orders, name='delivered_orders'),
    
    path('update_booking/<int:id>/<str:status>', views.update_booking, name='update_booking'),
    path('assign_vendor/<int:id>', views.assign_vendor, name='assign_vendor'),
    # Change Password
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='administrator/change_password.html',
            success_url = '/accounts/logout/'
        ),
        name='change_password'
    ),
     path(
        'vendor-change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='vendor/change_password.html',
            success_url = '/accounts/logout/'
        ),
        name='vendor_change_password'
    ),
    path(
        'customer-change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='shop/change_password.html',
            success_url = '/accounts/logout/'
        ),
        name='customer_change_password'
    ),
]

shop/urls.py
from django.urls import path
from shop import views
from django.contrib.auth import views as auth_views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.home, name='category_filter'),
    path('product-category/<slug:slug>/', views.products, name='products'),
  
    path('add_to_cart/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:id>', views.update_cart, name='update_cart'),
    path('del_cart/<int:id>', views.remove_from_cart, name='del_cart'),
    path('cart-list', views.cart_list, name='cart-list'),
    path('buy_now', views.buy_now, name='buy_now'),
    path('my_orders', views.my_orders, name='my_orders'),
    path('view_order/<int:id>', views.view_order, name='view_order'),
    path('invoice/<int:id>', views.invoice, name='invoice'),
    path('my_profile', views.my_profile, name='my_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('details/<int:id>/',views.detail,name="detail"),
    path('addreview/<int:id>/',views.add_review,name="add_review"),
    path('editreview/<int:product_id>/<int:review_id>',views.edit_review,name="edit_review"),
    path('deletereview/<int:product_id>/<int:review_id>',views.delete_review,name="delete_review"),
]

account/forms.py
from django import forms
from account.models import *
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class ProductForm(forms.ModelForm):
    vendor = forms.ModelChoiceField(queryset = User.objects.all(),widget=forms.Select(attrs={'class': 'form-control'}) )
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    category = forms.ModelChoiceField(queryset = Category.objects.all(),widget=forms.Select(attrs={'class': 'form-control'}) )
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    price = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    current_stock = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control','min':1}))
    class Meta:
        model = Product
        fields = ['name','category','description','price','image','vendor','current_stock']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment","rating")


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'full_name', 'phone_number')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise forms.ValidationError('passwords must match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'full_name', 'phone_number')

    def clean_password(self):
        return self.initial['password']


class UserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=12,widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('full_name', 'email', 'phone_number')

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=12,widget=forms.TextInput(attrs={'class': 'form-control'}))

templates/administrator/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title -->
    <title>Herbal & Agro Farming</title>
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/plugins/charts-c3/plugin.css' %}" />
<link rel="stylesheet" href="{% static 'assets/plugins/morrisjs/morris.min.css' %}" />

<link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
<style type="text/css">
    body {
                
                 background-color: #E6E6FA;
         }
</style>
</head>

<body class="theme-blush">

    <div class="page-loader-wrapper">
    <div class="loader">
    <div class="m-t-30"><img class="zmdi-hc-spin" src="assets/images/loader.svg" width="48" height="48" alt="Aero"></div>
    <p>Please wait...</p>
    </div>
    </div>
    
    <div class="overlay"></div>
    
    
    <aside id="leftsidebar" class="sidebar">
        <div class="navbar-brand">
        <button class="btn-menu ls-toggle-btn" type="button"><i class="zmdi zmdi-menu"></i></button>
        <a href="#"><span class="m-l-10"><b>Herbal & Agro Farming</b></span></a>
        </div>
        <div class="menu">
        <ul class="list">
        <li>
        <div class="user-info">
        <div class="detail">
        <h4></h4>
        <small><b>Admin</b></small>
        </div>
        </div>
        </li>
        <li class="active open"><a href="{% url 'account:admin_dashboard' %}"><i class="zmdi zmdi-home"></i><span><b>Dashboard</b></span></a></li>
        <li><a href="{% url 'account:categories-list' %}"><i class="zmdi zmdi-collection-item"></i><span><b>Categories</b></span></a></li>
        <li><a href="{% url 'account:products-list' %}"><i class="zmdi zmdi-apps"></i><span><b>Products</b></span></a></li>
        <li><a href="{% url 'account:vendor-list' %}"><i class="zmdi zmdi-accounts-alt"></i><span><b>Vendors</b></span></a></li>
        <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-local-shipping"></i><span><b>Orders</b></span></a>
        <ul class="ml-menu">
        <li><a href="{% url 'account:pending_orders' %}"><b>Pending</b></a></li>
        <li><a href="{% url 'account:canceled_orders' %}"><b>Canceled</b></a></li>
        <li><a href="{% url 'account:delivered_orders' %}"><b>Delivered</b></a></li>
        </ul>
        </li>
          <li><a href="{% url 'account:change_password' %}"><i class="zmdi zmdi-lock"></i><span><b>Change Password</b></span></a></li>
            <li><a href="{% url 'account:logout' %}"><i class="zmdi zmdi-power-off"></i><span><b>Logout</b></span></a></li>
    </ul>
</div>
</aside>
<section class="content">
    <!-- Content -->
    {% for message in messages %}
<script type="text/javascript">
  alert("{{message}}");
</script>
{% endfor %}

{% block main %}
{% endblock %}
<!-- End Content -->
</section>
<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script> 
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script> 
<script src="{% static 'assets/bundles/jvectormap.bundle.js' %}"></script> 
<script src="{% static 'assets/bundles/sparkline.bundle.js' %}"></script> 
<script src="{% static 'assets/bundles/c3.bundle.js' %}"></script>
<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'assets/js/pages/index.js' %}"></script>
</body>
</html>

templates/administrator/categories-list.html
{% extends 'administrator/base.html' %}
{% block main %}
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Disease List</h2>
                    
                    
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <a class="btn btn-primary float-right" type="button" href="{% url 'account:category-create' %}">Add New</a>
                </div>
            </div>
        </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12">
    <div class="card">
        <div class="body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                            	<tr>
                            		<th>#</th>
                            		<th>Disease Name</th>
                            		<th>Slug</th>
                            		<th>Edit</th>
                            		<th>Delete</th>
                            	</tr>
                            </thead>
                            <tbody>
                            	{% for category in categories %}
                            	<tr>
                            		<td> {{ forloop.counter }}</td>
                            		<td>{{category.name}}</td>
                            		<td>{{category.slug}}</td>
                            		<td><a class="btn btn-primary" href="{% url 'account:category_edit' category.id %}">Edit</a></td>
                            		<td><a class="btn btn-danger" href="{% url 'account:category_delete' category.id %}" onclick="return confirm('Are you sure you want to delete this?')">Delete</a></td>
                            	</tr>
                            	{% endfor %}
                            </tbody>
                        </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% include "administrator/dtscripts.html" %}
{% endblock %}

templates/administrator/category-create.html
{% extends 'administrator/base.html' %}
{% block main %}
<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>New Category</h2>
                
                
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                
            </div>
        </div>
    </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12">
<div class="card">
    <div class="body">
                <form action="#" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in category_form %}
                    
                        <div class="form-group lang_form">
                            <label class="input-label" for="exampleFormControlInput1">{{field.label}}</label>
                                                <input type="{{field.input_type}}" name="{{field.name}}" class="form-control" id="id_{{field.name}}"
                                                       placeholder="{{field.name}}" required>
                        </div>
                    
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Save</button>

                </form>
             </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>

{% endblock %}

templates/administrator/category-edit.html
{% extends 'administrator/base.html' %}
{% block main %}
<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Edit Category</h2>
                
                
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                
            </div>
        </div>
    </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12 col-md-12 col-sm-12">
<div class="card">
    <div class="body">
                <form action="#" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                        <div class="form-group lang_form">
                            <label class="input-label" for="exampleFormControlInput1">Category Name</label>
                                                <input type="text" name="name" class="form-control" id="id_name"
                                                       placeholder="Category Name" required value="{{category.name}}" pattern="[a-zA-Z]{2}[a-zA-Z\ ]*" title="Only Alphabets Allowed">
                        </div>
                    
                    <button type="submit" class="btn btn-primary">Update</button>

                </form>
             </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>

{% endblock %}

templates/administrator/delivered_orders.html
{% extends 'administrator/base.html' %}
{% block main %}
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Delivered  Product Orders</h2>
                    
                    
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                   
                </div>
            </div>
        </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12">
    <div class="card">
        <div class="body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Customer Name</th>
                                    <th>Mobile</th>
                                    <th>Email</th>
                                    <th>Shipping Address</th>
                                    <th>Order Date</th>
                                    
                                    <th>Total Order Amount</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                          {% for product_order in product_orders %}
                          <tr>
                              <td>{{ forloop.counter}}</td>
                              <td>{{ product_order.user.full_name}}</td>
                              <td>{{ product_order.user.phone_number}}</td>
                              <td>{{ product_order.user.email}}</td>
                              <td>{{ product_order.shipping_address}}</td>
                              <td>{{ product_order.order_date}}</td>
                              
                              <td>₹{{ product_order.total_order_amount}}/-</td>
                              <td><a class="btn btn-primary" href="{% url 'account:view_order' product_order.id %}">View Order</a></td>
                          </tr>
                          {% endfor %}
                            </tbody>
                        </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% include "administrator/dtscripts.html" %}
{% endblock %}

templates/administrator/dtscripts.html
{% load static %}
<script src="{% static 'assets/bundles/datatablescripts.bundle.js' %}"></script>
<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'assets/js/pages/tables/jquery-datatable.js' %}"></script>

templates/administrator/pending_orders.html
{% extends 'administrator/base.html' %}
{% block main %}
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Pending Product Orders</h2>
                    
                    
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    
                </div>
            </div>
        </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12">
    <div class="card">
        <div class="body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Customer Name</th>
                                    <th>Mobile</th>
                                    <th>Email</th>
                                    <th>Shipping Address</th>
                                    <th>Order Date</th>
                                    <th>Total Order Amount</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                          {% for product_order in product_orders %}
                          <tr>
                              <td>{{ forloop.counter}}</td>
                              <td>{{ product_order.user.full_name}}</td>
                              <td>{{ product_order.user.phone_number}}</td>
                              <td>{{ product_order.user.email}}</td>
                              <td>{{ product_order.shipping_address}}</td>
                              <td>{{ product_order.order_date}}</td>
                              
                              <td>₹{{ product_order.total_order_amount}}/-</td>
                              <td><a class="btn btn-success" href="{% url 'account:update_order' product_order.id 'Delivered' %}">Delivered</a><a class="btn btn-danger" href="{% url 'account:update_order' product_order.id 'Canceled' %}">Canceled</a><a class="btn btn-primary" href="{% url 'account:view_order' product_order.id %}">View Order</a></td>
                          </tr>
                          {% endfor %}
                            </tbody>
                        </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% include "administrator/dtscripts.html" %}
{% endblock %}

templates/administrator/products-list.html
{% extends 'administrator/base.html' %}
{% block main %}
<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Products List</h2>
                
                
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <a class="btn btn-primary float-right" type="button" href="{% url 'account:product-create' %}">Add New</a>
            </div>
        </div>
    </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12">
<div class="card">
    <div class="body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            	<tr>
                            		<th>#</th>
                                    <td>Vendor name</td>
                            		<th>Product Name</th>
                                    <th>Category</th>
                            		<th>Slug</th>
                                    <th>Image</th>
                                    <th>Description</th>
                                    <th>Price</th>
                                    <th>Current Stock</th>
                                   
                            		<th>Edit</th>
                            		<th>Delete</th>
                            	</tr>
                            </thead>
                            <tbody>
                            	{% for product in products %}
                            	<tr>
                            		<td> {{ forloop.counter }}</td>
                                    <td> {{product.vendor.full_name}}</td>
                            		<td>{{product.name}}</td>
                                    <td>{{product.category.name}}</td>
                            		<td>{{product.slug}}</td>
                                    <td><img src="../../media/{{product.image}}" width="100" /></td>
                                    <td>{{product.description}}</td>
                                    <td>₹{{product.price}}/-</td>
                                    <td>{{product.current_stock}}</td>

                            		<td><a class="btn btn-primary" href="{% url 'account:product_edit' product.id %}">Edit</a></td>
                            		<td><a class="btn btn-danger" href="{% url 'account:product_delete' product.id %}" onclick="return confirm('Are you sure you want to delete this?')">Delete</a></td>
                            	</tr>
                            	{% endfor %}
                            </tbody>
                        </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% include "administrator/dtscripts.html" %}
{% endblock %}

templates/administrator/vendor-list.html
{% extends 'administrator/base.html' %}
{% block main %}
<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Vendors List</h2>
                
                
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
               
            </div>
        </div>
    </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12">
<div class="card">
    <div class="body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            	<tr>
                            		<th>#</th>
                            		<th>Vendor Name</th>
                                    <th>Mobile</th>
                                    <th>Email</th>
                            		<th>Edit</th>
                            		<th>Delete</th>
                            	</tr>
                            </thead>
                            <tbody>
                            	{% for vendor in vendors %}
                            	<tr>
                            		<td> {{ forloop.counter }}</td>
                            		<td>{{vendor.full_name}}</td>
                                    <td>{{vendor.phone_number}}</td>
                                    <td>{{vendor.email}}</td>
                            		<td><a class="btn btn-primary" href="{% url 'account:vendor_edit' vendor.id %}">Edit</a></td>
                            		<td><a class="btn btn-danger" href="{% url 'account:vendor_delete' vendor.id %}" onclick="return confirm('Are you sure you want to delete this?')">Delete</a></td>
                            	</tr>
                            	{% endfor %}
                            </tbody>
                        </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% include "administrator/dtscripts.html" %}
{% endblock %}

templates/administrator/view_order.html
{% extends 'administrator/base.html' %}
{% block main %}
<div class="body_scroll">
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Products List</h2>
                
                
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <a class="btn btn-primary float-right" type="button" href="{% url 'account:product-create' %}">Add New</a>
            </div>
        </div>
    </div>
<div class="container-fluid">
<div class="row clearfix">
<div class="col-lg-12">
<div class="card">
    <div class="body">
        <div class="table-responsive">
           
            <table class="table table-bordered table-striped table-hover js-basic-example">
                    <tr>
                        <th>Order Date</th>
                        <td>{{ product_order.order_date}}</td>
                        <th>Order Status</th>
                        <td>{{ product_order.order_status}}</td>
                        <th>Delivery Status</th>
                        <td>{{ product_order.delivery_status}}</td>
                        <th>Total Order Amount</th>
                        <td>₹{{ product_order.total_order_amount}}/-</td>
                    </tr>
            </table>
            <table class="table table-bordered table-striped table-hover js-basic-example">
                    <tr>
                        <th>#</th>
                         <th style="text-align:center">Vendor</th>
                        <th style="text-align:center">Product</th>
                        <th style="text-align:center">Quantity</th>
                        <th style="text-align:center">Price</th>
                        <th style="text-align:center">Amount</th>
                  
                    </tr>

              {% for order_item in order_items %}
              <tr>
                  <td>{{ forloop.counter}}</td>
                   <td >{{ order_item.product.vendor.full_name}}</td>
                  <td>{{ order_item.product.name}}
                      <br><img src="{{ order_item.product.image.url}}" width="100"/>
                  </td>
                  <td style="text-align:center"> {{ order_item.quantity}}</td>
                  <td style="text-align:right">₹{{ order_item.product.price}}/-</td>
                  <td style="text-align:right">₹{{ order_item.amount}}/-</td>
                  
              </tr>
              
              {% endfor %}
              <tr>
                <td colspan="4" style="text-align:right;">Total Amount</td>
                <td  style="text-align:right">₹{{product_order.total_order_amount}}/-</td>
                
              </tr>
            </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% include "administrator/dtscripts.html" %}
{% endblock %}